# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-12 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate1',
            fields=[
                ('C1_id', models.AutoField(help_text='自动生成，主键，不能为空值', primary_key=True, serialize=False, verbose_name='一级分类ID')),
                ('C1_name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('C1_shorthand', models.CharField(max_length=2, verbose_name='名称简写')),
            ],
            options={
                'verbose_name': '一级分类',
            },
        ),
        migrations.CreateModel(
            name='Cate2',
            fields=[
                ('C2_id', models.AutoField(help_text='自动生成，主键，不能为空值', primary_key=True, serialize=False, verbose_name='二级分类ID')),
                ('C2_name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('C2_shorthand', models.CharField(max_length=2, verbose_name='名称简写')),
                ('FK_C1id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Cate1')),
            ],
        ),
        migrations.CreateModel(
            name='Cate3',
            fields=[
                ('C3_id', models.AutoField(help_text='自动生成，主键，不能为空值', primary_key=True, serialize=False, verbose_name='三级分类ID')),
                ('C2_name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('C2_shorthand', models.CharField(max_length=2, verbose_name='名称简写')),
                ('FK_C2id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Cate2')),
            ],
        ),
        migrations.CreateModel(
            name='cost',
            fields=[
                ('c_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='序号')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('C1', models.CharField(max_length=16, verbose_name='一级科目')),
                ('C2', models.CharField(max_length=16, verbose_name='二级科目')),
                ('C3', models.CharField(max_length=16, verbose_name='三级科目')),
                ('summary', models.CharField(max_length=500, verbose_name='摘要')),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='发生金额')),
                ('BorL', models.CharField(choices=[('借', '借'), ('贷', '贷')], max_length=2, verbose_name='借贷方向')),
                ('Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='当前余额')),
                ('Account_number', models.CharField(max_length=40, verbose_name='结算账号')),
                ('Manager', models.CharField(max_length=26, verbose_name='经办人')),
                ('Settlement', models.CharField(choices=[('是', '是'), ('否', '否')], max_length=2, verbose_name='是否结算')),
                ('S_date', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
            ],
        ),
        migrations.CreateModel(
            name='km_c1',
            fields=[
                ('KC1_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('KC1_name', models.CharField(max_length=200, verbose_name='科目名称')),
            ],
        ),
        migrations.CreateModel(
            name='km_c2',
            fields=[
                ('KC2_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('KC2_name', models.CharField(max_length=200, verbose_name='科目名称')),
                ('id_kc1_kc2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.km_c1')),
            ],
        ),
        migrations.CreateModel(
            name='km_c3',
            fields=[
                ('KC3_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('KC3_name', models.CharField(max_length=200, verbose_name='科目名称')),
                ('id_kc2_kc3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.km_c2')),
            ],
        ),
    ]
