# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-12 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='km_c1',
            name='KC1_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='科目名称'),
        ),
        migrations.AlterField(
            model_name='km_c2',
            name='KC2_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='科目名称'),
        ),
        migrations.AlterField(
            model_name='km_c3',
            name='KC3_name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='科目名称'),
        ),
    ]
