# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20170312_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPC',
            fields=[
                ('UPC', models.IntegerField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('Used', models.CharField(choices=[('Y', '是'), ('N', '否')], max_length=1, verbose_name='是否使用')),
                ('U_date', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('sku', models.CharField(max_length=200, unique=True, verbose_name='对应SKU')),
                ('Asin', models.CharField(max_length=12, verbose_name='对应ASIN')),
            ],
        ),
    ]
