# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20170312_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upc',
            name='U_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用时间'),
        ),
    ]
