# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20170312_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='颜色')),
                ('color_name_cn', models.CharField(max_length=100, verbose_name='中文')),
            ],
        ),
        migrations.CreateModel(
            name='P_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_org', models.ImageField(upload_to='product_image/1496044694.858991/', verbose_name='原图')),
                ('image_big', models.ImageField(max_length=255, upload_to='', verbose_name='大图')),
                ('image_128_128', models.ImageField(max_length=255, upload_to='', verbose_name='中图')),
                ('image_64_64', models.ImageField(max_length=255, upload_to='', verbose_name='小图')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='产品ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('p_c1', models.CharField(max_length=255, verbose_name='一级分类')),
                ('p_c2', models.CharField(max_length=255, verbose_name='二级分类')),
                ('p_c3', models.CharField(max_length=255, verbose_name='三级分类')),
                ('p_img', models.ImageField(upload_to='/media/', verbose_name='产品图片')),
                ('P_size', models.CharField(max_length=255, verbose_name='尺码')),
                ('P_color', models.CharField(max_length=255, verbose_name='颜色')),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本价')),
                ('p_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折扣')),
            ],
        ),
        migrations.CreateModel(
            name='Product_ext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255, verbose_name='供应商')),
                ('Item_number', models.CharField(max_length=255, verbose_name='货号')),
                ('Product_source', models.URLField(max_length=255, verbose_name='采购链接')),
                ('supplier_code', models.CharField(max_length=255, verbose_name='供应商条码')),
                ('ext_size_us', models.CharField(max_length=255, verbose_name='US码')),
                ('ex_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('Size_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='尺码')),
            ],
        ),
        migrations.AlterField(
            model_name='cost',
            name='create_date',
            field=models.DateTimeField(verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='km_c1',
            name='KC1_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='一级科目'),
        ),
        migrations.AlterField(
            model_name='km_c2',
            name='KC2_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='二级科目'),
        ),
        migrations.AlterField(
            model_name='km_c3',
            name='KC3_name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='三级科目'),
        ),
        migrations.AddField(
            model_name='p_image',
            name='img_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product'),
        ),
    ]
