# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_auto_20170529_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='Ext_name_1',
            field=models.CharField(max_length=255, null=True, verbose_name='尺码别名'),
        ),
        migrations.AlterField(
            model_name='p_image',
            name='image_org',
            field=models.ImageField(upload_to='product_image/1496045695.404056/', verbose_name='原图'),
        ),
    ]
