# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-29 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20170529_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_image',
            name='image_org',
            field=models.ImageField(upload_to='product_image/1496049148.2905498/', verbose_name='原图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_img',
            field=models.ImageField(null=True, upload_to='/media/', verbose_name='产品图片'),
        ),
    ]
